In [1]:
#import required libraries
import numpy as np
import pandas as pd

In [2]:
#Load train dataset
data=pd.read_csv('C:/Users/Abir Khan/Desktop/Dataset for the project/train/train.csv')
datatest=pd.read_csv('C:/Users/Abir Khan/Desktop/Dataset for the project/test/test.csv')
data.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [3]:
#Get details for data

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB

In [4]:
#Remove columns with variance 0 as those columns will not impact the prediction and mostly those will have constant data
#to reduce number of cols remve those var=0 cols

data.var()[data.var()==0].index.values

array(['X11', 'X93', 'X107', 'X233', 'X235', 'X268', 'X289', 'X290',
       'X293', 'X297', 'X330', 'X347'], dtype=object)

In [5]:
#drop 0 var columns
datafinal=data.drop(data.var()[data.var()==0].index.values, axis=1)
datafinal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 366 entries, ID to X385
dtypes: float64(1), int64(357), object(8)
memory usage: 11.8+ MB

In [6]:
#get features and labels

features=datafinal.iloc[:,2:]
label=datafinal.iloc[:,1].values

In [7]:
features.head()

,X0,X1,X2,X3,X4,X5,X6,X8,X10,X12,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,k,v,at,a,d,u,j,o,0,0,...,0,0,1,0,0,0,0,0,0,0
1,k,t,av,e,d,y,l,o,0,0,...,1,0,0,0,0,0,0,0,0,0
2,az,w,n,c,d,x,j,x,0,0,...,0,0,0,0,0,0,1,0,0,0
3,az,t,n,f,d,x,l,e,0,0,...,0,0,0,0,0,0,0,0,0,0
4,az,v,n,f,d,h,d,n,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
#Get object columns from feature column for LE and OHE

features.describe(include=['object'])

          X0    X1    X2    X3    X4    X5    X6    X8
count   4209  4209  4209  4209  4209  4209  4209  4209
unique    47    27    44     7     4    29    12    25
top        z    aa    as     c     d     v     g     j
freq     360   833  1659  1942  4205   231  1042   277

In [9]:
#Get only object column names

objcols=features.describe(include=['object']).columns.values
objcols

array(['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8'], dtype=object)

In [10]:
#Apply Label Encoder  for object columns. OHE is not use das this will create PC's instead of using direct variables

from sklearn.preprocessing import LabelEncoder
#from sklearn.preprocessing import OneHotEncoder

le=LabelEncoder()

for i in objcols:
  features[i]= le.fit_transform(features[i])

#ohe=OneHotEncoder(categorical_features=[0,1,2,3,4,5,6,8])

fea=features.values
#featureohe=fea #ohe.fit_transform(fea).toarray()

#featureohe
fea

array([[32, 23, 17, ...,  0,  0,  0],
       [32, 21, 19, ...,  0,  0,  0],
       [20, 24, 34, ...,  0,  0,  0],
       ...,
       [ 8, 23, 38, ...,  0,  0,  0],
       [ 9, 19, 25, ...,  0,  0,  0],
       [46, 19,  3, ...,  0,  0,  0]], dtype=int64)

In [11]:
#Standardize the data using StandardScaler

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
featuresstd = sc.fit_transform(fea)

In [12]:
#USe PCA for dimensionality reduction
#Use no of components as ALL column to identify correct number of componnets
from sklearn.decomposition import PCA

pca = PCA(n_components=364, svd_solver='full')
pca.fit(featuresstd,label)

PCA(copy=True, iterated_power='auto', n_components=364, random_state=None,
    svd_solver='full', tol=0.0, whiten=False)

In [13]:
#check explained variance ratio
pca.explained_variance_ratio_

array([6.89266892e-02, 5.68841213e-02, 4.53745695e-02, 3.42677135e-02,
       3.26430877e-02, 3.16266067e-02, 2.86252442e-02, 2.12375123e-02,
       1.97041337e-02, 1.78319550e-02, 1.64006646e-02, 1.56428622e-02,
       1.46274226e-02, 1.44833491e-02, 1.34828580e-02, 1.29516175e-02,
       1.24383219e-02, 1.17310333e-02, 1.12105051e-02, 1.07727793e-02,
       9.92512898e-03, 9.69449157e-03, 9.42523076e-03, 9.09867975e-03,
       8.74223908e-03, 8.43069482e-03, 7.90204943e-03, 7.63217614e-03,
       7.33541876e-03, 7.14905572e-03, 6.92957269e-03, 6.76677298e-03,
       6.52534438e-03, 6.41494089e-03, 6.22692040e-03, 5.99196153e-03,
       5.88086185e-03, 5.74693562e-03, 5.63702738e-03, 5.53409616e-03,
       5.50641149e-03, 5.40082599e-03, 5.33910600e-03, 5.24611598e-03,
       5.10194247e-03, 5.03232420e-03, 4.95885463e-03, 4.72691565e-03,
       4.64475228e-03, 4.56521484e-03, 4.39624472e-03, 4.32947533e-03,
       4.30322432e-03, 4.23762131e-03, 4.20211958e-03, 4.15473420e-03,
       4.06699537e-03, 4.03462750e-03, 3.91873995e-03, 3.88747084e-03,
       3.81759321e-03, 3.75560105e-03, 3.72440051e-03, 3.65910562e-03,
       3.59566547e-03, 3.55229656e-03, 3.49700953e-03, 3.46182278e-03,
       3.40471717e-03, 3.34157815e-03, 3.30984908e-03, 3.25521932e-03,
       3.24084510e-03, 3.21045090e-03, 3.16671200e-03, 3.16169105e-03,
       3.09963730e-03, 3.07579140e-03, 3.05317642e-03, 3.03955238e-03,
       3.00255847e-03, 2.98903148e-03, 2.95834824e-03, 2.92906873e-03,
       2.90789282e-03, 2.89246840e-03, 2.87088871e-03, 2.84861071e-03,
       2.82893540e-03, 2.80661865e-03, 2.79489424e-03, 2.76964748e-03,
       2.74977677e-03, 2.72538185e-03, 2.72396743e-03, 2.66915947e-03,
       2.64849773e-03, 2.63035478e-03, 2.60995440e-03, 2.60665425e-03,
       2.57383600e-03, 2.54968974e-03, 2.53621249e-03, 2.51953928e-03,
       2.50398175e-03, 2.48457976e-03, 2.44053200e-03, 2.42183601e-03,
       2.40353580e-03, 2.38432335e-03, 2.34517965e-03, 2.31166118e-03,
       2.30049772e-03, 2.27223313e-03, 2.25613123e-03, 2.23532575e-03,
       2.21465563e-03, 2.20028258e-03, 2.15055308e-03, 2.13667795e-03,
       2.10335610e-03, 2.09410362e-03, 2.05842058e-03, 2.04122098e-03,
       2.02468809e-03, 1.98912003e-03, 1.93876262e-03, 1.91967571e-03,
       1.91801301e-03, 1.87935329e-03, 1.85171337e-03, 1.81419321e-03,
       1.79357485e-03, 1.78621289e-03, 1.75392321e-03, 1.71752943e-03,
       1.70719881e-03, 1.67983148e-03, 1.65808186e-03, 1.61860975e-03,
       1.61139410e-03, 1.57706719e-03, 1.54261681e-03, 1.53538284e-03,
       1.49678823e-03, 1.49384890e-03, 1.47852266e-03, 1.42828100e-03,
       1.41108081e-03, 1.37376476e-03, 1.33814992e-03, 1.28803283e-03,
       1.26972355e-03, 1.26213163e-03, 1.20721187e-03, 1.16191771e-03,
       1.14336841e-03, 1.12752230e-03, 1.09498612e-03, 1.05869705e-03,
       9.99910624e-04, 9.89110199e-04, 9.86361463e-04, 9.54546927e-04,
       9.45056062e-04, 9.11514885e-04, 8.99355342e-04, 8.80886749e-04,
       8.63653466e-04, 8.59439761e-04, 8.29410991e-04, 8.24059997e-04,
       7.98201807e-04, 7.91126650e-04, 7.78713087e-04, 7.44845247e-04,
       7.24330743e-04, 7.08041140e-04, 6.85829934e-04, 6.72145117e-04,
       6.55718352e-04, 6.40733883e-04, 6.12000447e-04, 5.86075445e-04,
       5.58289468e-04, 5.45679895e-04, 5.41944228e-04, 5.30507026e-04,
       5.23125193e-04, 5.09290043e-04, 4.93967305e-04, 4.75601629e-04,
       4.59394696e-04, 4.52812516e-04, 4.39558529e-04, 4.26949429e-04,
       4.14907621e-04, 4.07139378e-04, 3.99902280e-04, 3.96288548e-04,
       3.86933450e-04, 3.72623799e-04, 3.62443593e-04, 3.54579912e-04,
       3.38415435e-04, 3.29616574e-04, 3.16880863e-04, 3.07011359e-04,
       2.91609975e-04, 2.84735221e-04, 2.74172380e-04, 2.65105542e-04,
       2.57082857e-04, 2.44896369e-04, 2.37787938e-04, 2.29725881e-04,
       2.28237225e-04, 2.26852369e-04, 2.18016571e-04, 2.09597981e-04,
       1.98544338e-04, 1.74896477e-04, 1.63275485e-04, 1.56435191e-04,
       1.48275745e-04, 1.45817565e-04, 1.39375105e-04, 1.25010833e-04,
       1.16516633e-04, 1.08763512e-04, 1.00668042e-04, 9.32800134e-05,
       8.37733596e-05, 7.81804284e-05, 6.89060898e-05, 6.38124700e-05,
       6.20529750e-05, 5.69132679e-05, 4.99048590e-05, 4.85560153e-05,
       4.49553468e-05, 4.31149301e-05, 4.23039470e-05, 3.76702109e-05,
       3.67759864e-05, 3.16512054e-05, 3.01120917e-05, 2.60667672e-05,
       2.04349916e-05, 1.43314337e-05, 1.24786542e-05, 1.17912074e-05,
       8.13427984e-06, 7.14835152e-06, 4.73619419e-06, 4.54880789e-06,
       3.00516288e-06, 2.48700880e-06, 1.42103632e-06, 1.35933926e-32,
       2.03775596e-33, 2.02531407e-33, 1.60817378e-33, 1.41392516e-33,
       1.33726553e-33, 1.22379355e-33, 1.15927483e-33, 1.02240091e-33,
       8.55156440e-34, 7.95844170e-34, 7.22863434e-34, 5.69909583e-34,
       4.18902155e-34, 3.55687842e-34, 3.16603046e-34, 3.14824492e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 3.12692316e-34, 3.12692316e-34,
       3.12692316e-34, 3.12692316e-34, 2.81099293e-34, 1.85208053e-34,
       1.67229422e-34, 8.96352520e-35, 2.99729856e-35, 3.46465135e-36])

In [14]:
#Get mean of explained variance ratio to get the threshold value for varince
np.mean(pca.explained_variance_ratio_)

0.002747252747252748

In [15]:
#Check number of components which has explained variance >threshold value
pca.explained_variance_ratio_>0.002747252747252748

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [16]:
#PCA with n components 93 which has explained variance ratio >threshold

pca = PCA(n_components=93,svd_solver='full')
pca.fit(featuresstd,label)

finalFeatures = pca.transform(featuresstd)
finalFeatures.shape

(4209, 93)

In [17]:
label.shape

(4209,)

In [18]:
#Used No of splits for sample from 5 and increased to 5, 10 ,20,30 etc till 1000. Got a better generalized model at split=1000

from sklearn.model_selection import KFold
from xgboost import XGBRegressor

kfold=KFold(n_splits=1000,
           random_state=1,
           shuffle=True)
#kfold.split(finalFeatures)

i=0
for train,test in kfold.split(finalFeatures):
    i = i+1
    X_train,X_test = finalFeatures[train],finalFeatures[test]
    y_train,y_test = label[train],label[test]
    model = XGBRegressor(objective='reg:squarederror', learnning_rate=0.1)
    
    model.fit(X_train,y_train)
    
    if model.score(X_test,y_test) > 0.93: #model.score(X_train, y_train)
        print("Test Score: {}, train score: {}, for Sample Split: {}".format(model.score(X_test,y_test),model.score(X_train,y_train),i))

Test Score: 0.974017880163746, train score: 0.9521955868685419, for Sample Split: 1
Test Score: 0.956831098974932, train score: 0.9536994004834016, for Sample Split: 197
Test Score: 0.963151383843318, train score: 0.9546399631171532, for Sample Split: 269
Test Score: 0.9409404612525819, train score: 0.9519535825213398, for Sample Split: 322
Test Score: 0.9663734875179674, train score: 0.9541527439570472, for Sample Split: 368
Test Score: 0.9381214149049936, train score: 0.9523292344027178, for Sample Split: 401
Test Score: 0.930414491529307, train score: 0.9525544559427448, for Sample Split: 550
Test Score: 0.9483371975226297, train score: 0.951163375156542, for Sample Split: 596
Test Score: 0.943180985125625, train score: 0.9537225405151459, for Sample Split: 597
Test Score: 0.935972658000711, train score: 0.9551835316270261, for Sample Split: 616
Test Score: 0.9436953116558963, train score: 0.9534229257455195, for Sample Split: 635
Test Score: 0.9515860157822272, train score: 0.9528739593456859, for Sample Split: 653
Test Score: 0.9392788464786749, train score: 0.9531626828325203, for Sample Split: 679
Test Score: 0.9562002797535781, train score: 0.9537764784135778, for Sample Split: 686
Test Score: 0.9677029444051742, train score: 0.9549926864978735, for Sample Split: 695
Test Score: 0.9552822698956538, train score: 0.9514649926773036, for Sample Split: 717
Test Score: 0.9312280955297326, train score: 0.9526828734518655, for Sample Split: 731
Test Score: 0.9635122947791769, train score: 0.9533882540172046, for Sample Split: 733
Test Score: 0.9515427414071743, train score: 0.9507280138047777, for Sample Split: 771
Test Score: 0.9331922967899607, train score: 0.9507596176379651, for Sample Split: 840
Test Score: 0.9314924428076733, train score: 0.9529539975713827, for Sample Split: 844
Test Score: 0.9444095542160114, train score: 0.9560732583004212, for Sample Split: 869
Test Score: 0.9802252551457228, train score: 0.9526122896011493, for Sample Split: 889
Test Score: 0.9523652770809964, train score: 0.9525664772888969, for Sample Split: 968

In [20]:
#Test Score: 0.9802252551457228, train score: 0.9526122896011493, for Sample Split: 889
#Extract sample at value 889 with split 1000

kfold = KFold(n_splits=1000, 
              random_state=1,
              shuffle=True)
i=0
for train,test in kfold.split(finalFeatures):
    i = i+1
    if i == 889:
        X_train,X_test,y_train,y_test = finalFeatures[train],finalFeatures[test],label[train],label[test]

In [21]:
#fit into model and get scores using XGBoost regression

model = XGBRegressor(objective='reg:squarederror', learnning_rate=0.1)
    
model.fit(X_train,y_train)

#Check the quality of model
print("Training Accuracy ",model.score(X_train,y_train))
print("Testing Accuracy ",model.score(X_test,y_test))

Training Accuracy  0.9526122896011493
Testing Accuracy  0.9802252551457228

In [22]:
#Check model accuracy and error metrices

from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

#MAE - check this error metrics. 
mean_absolute_error(y_test,model.predict(X_test))

1.4400474548339837

In [23]:
#MAE is low which gives high accuracy
#Check modle accuracy based on R2
r2_score(y_test,model.predict(X_test), multioutput='variance_weighted')

0.9802252551457228

In [24]:
#R2 also gives good accuracy. 
#So accept this model
#Check MSE
mean_squared_error(y_test,model.predict(X_test))

3.1538612032245354

In [25]:
#Now read and process test data file and predict Y value

datatest.head()

,ID,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,1,az,v,n,f,d,t,a,w,0,...,0,0,0,1,0,0,0,0,0,0
1,2,t,b,ai,a,d,b,g,y,0,...,0,0,1,0,0,0,0,0,0,0
2,3,az,v,as,f,d,a,j,j,0,...,0,0,0,1,0,0,0,0,0,0
3,4,az,l,n,f,d,z,l,n,0,...,0,0,0,1,0,0,0,0,0,0
4,5,w,s,as,c,d,y,i,m,0,...,1,0,0,0,0,0,0,0,0,0

In [26]:
#Remove same columns as we did for tain dataset
#'X11', 'X93', 'X107', 'X233', 'X235', 'X268', 'X289', 'X290',
      # 'X293', 'X297', 'X330', 'X347'

datafinal=datatest.drop(['X11', 'X93', 'X107', 'X233', 'X235', 'X268', 'X289', 'X290','X293', 'X297', 'X330', 'X347'], axis=1)
datafinal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 365 entries, ID to X385
dtypes: int64(357), object(8)
memory usage: 11.7+ MB

In [27]:
#Get feature columns

testFeatures=datafinal.iloc[:,1:]

#get object columns

objcolstest=testFeatures.describe(include=['object']).columns.values
objcolstest

array(['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8'], dtype=object)

In [28]:

#Apply Label Encoder  for object columns. 

from sklearn.preprocessing import LabelEncoder
#from sklearn.preprocessing import OneHotEncoder

le=LabelEncoder()

for i in objcolstest:
  testFeatures[i]= le.fit_transform(testFeatures[i])

f1=testFeatures.values


f1.ndim

2

In [29]:
#transform test data using PCA

transformFromPCA = pca.transform(f1)


labelpred=model.predict(transformFromPCA)
labelpred

array([109.37039 ,  89.3782  ,  92.38034 , ...,  93.89875 , 106.499275,
        86.42836 ], dtype=float32)

In [30]:
#Append Y predicted avlue in test data set

testdataforfile=pd.concat([datatest.iloc[:,0],pd.concat([pd.DataFrame(data=labelpred, columns=['y']),datatest.iloc[:,1:]], axis=1)],axis=1)

testdataforfile.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,1,109.370392,az,v,n,f,d,t,a,w,...,0,0,0,1,0,0,0,0,0,0
1,2,89.378197,t,b,ai,a,d,b,g,y,...,0,0,1,0,0,0,0,0,0,0
2,3,92.380341,az,v,as,f,d,a,j,j,...,0,0,0,1,0,0,0,0,0,0
3,4,99.932404,az,l,n,f,d,z,l,n,...,0,0,0,1,0,0,0,0,0,0
4,5,108.738327,w,s,as,c,d,y,i,m,...,1,0,0,0,0,0,0,0,0,0